[server]
maxUploadSize = 1000

# Optional: disable CORS if testing locally
enableCORS = false

# Optional: allow fileWatcher to detect changes quickly
fileWatcherType = "poll"

[theme]
primaryColor = "#667eea"
backgroundColor = "#f8fafc"
secondaryBackgroundColor = "#ffffff"
textColor = "#2d3748"
font = "Inter"

[ui]
navigationStyle = "collapsed"
